### SELECTION TECHNIQUES

In [2]:
import numpy as np

In [3]:
sample_array=np.arange(1,20)

In [4]:
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [5]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [6]:
np.exp(sample_array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [7]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [8]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [9]:
np.max(sample_array)

19

In [10]:
np.min(sample_array)

1

In [11]:
np.argmax(sample_array)

18

In [12]:
np.argmin(sample_array)

0

In [13]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361])

In [15]:
np.std(sample_array)

5.477225575051661

In [16]:
np.var(sample_array)

30.0

In [17]:
np.mean(sample_array)

10.0

In [18]:
array=np.random.randn(3,4)

In [19]:
array

array([[ 0.37432514,  0.22037674,  0.2474332 ,  0.35606822],
       [-0.25084204, -1.12466028,  0.04122218, -0.22893389],
       [-1.55822178, -0.0564243 ,  1.06238917,  0.81032233]])

In [21]:
np.round(array,decimals=2)

array([[ 0.37,  0.22,  0.25,  0.36],
       [-0.25, -1.12,  0.04, -0.23],
       [-1.56, -0.06,  1.06,  0.81]])

In [22]:
sports=np.array(['golf','cricket','tennis','cricket'])
sports

array(['golf', 'cricket', 'tennis', 'cricket'], dtype='<U7')

In [23]:
np.unique(sports)   # unique-> output is not repeted 

array(['cricket', 'golf', 'tennis'], dtype='<U7')

### PANDAS

In [24]:
import pandas as pd
import numpy as np

### PANDAS DATAFRAME AND INDEXING

In [28]:
sports1=pd.Series([1,2,3,4],index=['A', 'B',  'C',  'D '])  #Series-> single(2 columns) dataframe-> multiple
sports1

A     1
B     2
C     3
D     4
dtype: int64

In [30]:
sports1['A']

1

In [31]:
sports2=pd.Series([1,3,5,6,4], index=['A','B','C','E','Y'])
sports2

A    1
B    3
C    5
E    6
Y    4
dtype: int64

In [32]:
sports1+sports2

A     2.0
B     5.0
C     8.0
D     NaN
E     NaN
Y     NaN
dtype: float64

In [33]:
import pandas as pd
import numpy as np

In [35]:
df1=pd.DataFrame(np.random.rand(8,5),index='A B C D E F G H '.split(),columns='SCORE1 SCORE2 SCORE3 SCORE4 SCORE5'.split()) #split->to seperate
df1

SCORE1    SCORE2    SCORE3    SCORE4    SCORE5
A  0.095751  0.414162  0.219132  0.601804  0.097380
B  0.045007  0.259507  0.523077  0.640826  0.306919
C  0.948638  0.699578  0.184118  0.568388  0.274205
D  0.547286  0.836453  0.928116  0.461833  0.773690
E  0.270911  0.927075  0.004500  0.961119  0.416050
F  0.903454  0.382251  0.031007  0.405612  0.483229
G  0.562845  0.209146  0.519140  0.579332  0.070027
H  0.467093  0.277082  0.979479  0.883160  0.509614

In [38]:
df1["SCORE5"]

A    0.097380
B    0.306919
C    0.274205
D    0.773690
E    0.416050
F    0.483229
G    0.070027
H    0.509614
Name: SCORE5, dtype: float64

In [39]:
df1['SCORE6']=df1['SCORE1']+df1['SCORE3']

In [40]:
df1

SCORE1    SCORE2    SCORE3    SCORE4    SCORE5    SCORE6
A  0.095751  0.414162  0.219132  0.601804  0.097380  0.314883
B  0.045007  0.259507  0.523077  0.640826  0.306919  0.568083
C  0.948638  0.699578  0.184118  0.568388  0.274205  1.132756
D  0.547286  0.836453  0.928116  0.461833  0.773690  1.475402
E  0.270911  0.927075  0.004500  0.961119  0.416050  0.275411
F  0.903454  0.382251  0.031007  0.405612  0.483229  0.934461
G  0.562845  0.209146  0.519140  0.579332  0.070027  1.081985
H  0.467093  0.277082  0.979479  0.883160  0.509614  1.446573

In [41]:
df2={'ID':['101','102','103','104'], 'NAME':['DRAKE','ARON','ALAN','JAY'] , 'PROFIT':[20,31,45,67]}
df=pd.DataFrame(df2)
df

ID   NAME  PROFIT
0  101  DRAKE      20
1  102   ARON      31
2  103   ALAN      45
3  104    JAY      67

In [42]:
df['ID']

0    101
1    102
2    103
3    104
Name: ID, dtype: object

In [45]:
df=df.drop('ID', axis=1) #axis->which column starting with 0

In [46]:
df

NAME  PROFIT
0  DRAKE      20
1   ARON      31
2   ALAN      45
3    JAY      67

In [47]:
df.drop(3)

NAME  PROFIT
0  DRAKE      20
1   ARON      31
2   ALAN      45