In [1]:
import numpy as np


In [2]:
sample_list=[6,7,9]
np.array(sample_list)

array([6, 7, 9])

In [3]:
arr=np.array([6,7,9])
arr

array([6, 7, 9])

In [6]:
list_of_lists=[[1,2,3],[4,5,6],[7,8,9]]
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [9]:
np.arange(1,20)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [10]:
np.arange(1,31,5)   # shift+tab->helpbox

array([ 1,  6, 11, 16, 21, 26])

In [11]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [13]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [15]:
np.ones(10,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [16]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.ones(10,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [18]:
np.zeros((2,3),int)

array([[0, 0, 0],
       [0, 0, 0]])

In [19]:
np.linspace(1,31,5)

array([ 1. ,  8.5, 16. , 23.5, 31. ])

In [24]:
np.eye((10))

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [25]:
np.random.rand(2,4)

array([[0.8752869 , 0.61539069, 0.21048874, 0.46892325],
       [0.3836043 , 0.76234112, 0.96951699, 0.42583239]])

In [28]:
np.random.randint(2,4)

2

In [30]:
arr=np.random.randn(2,4)
arr

array([[-1.15012437, -0.08359437, -0.41475147, -0.80751876],
       [-0.05438841, -1.20056014, -0.96490383, -0.13093654]])

In [32]:
np.random.randint(2,20,10)

array([13,  4,  8,  8, 13,  5,  9,  5,  9, 18])

In [69]:
sarr=np.random.randint(0,100,20)
sarr

array([ 6, 92, 82, 29, 66, 60, 58, 77, 20,  6, 16, 51, 41, 70,  3, 97, 69,
       81, 52, 27])

In [43]:
sample_arr=np.arange(30)
sample_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [44]:
sample_arr.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [45]:
sample_arr.reshape(4,3)

ValueError: cannot reshape array of size 30 into shape (4,3)

In [70]:
sarr.max()   #max of arr

97

In [71]:
sarr.argmax() #argmax->index

15

In [49]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [50]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [51]:
a=np.random.rand(2,3)
a

array([[0.29404025, 0.33063419, 0.16792887],
       [0.10403583, 0.83324104, 0.08173173]])

In [52]:
a.T

array([[0.29404025, 0.10403583],
       [0.33063419, 0.83324104],
       [0.16792887, 0.08173173]])

In [56]:
sample_arr=np.arange(1,10)
sample_arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
sample_arr[1]

2

In [60]:
sample_arr[1:7]

array([2, 3, 4, 5, 6, 7])

In [62]:
sample_arr[1:7]=10
sample_arr

array([ 1, 10, 10, 10, 10, 10, 10,  8,  9])

In [63]:
sample_arr=np.arange(10,21)
sample_arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [64]:
sample_arr[2:6]

array([12, 13, 14, 15])

In [66]:
subset_sample_arr=sample_arr[2:6]
subset_sample_arr

array([12, 13, 14, 15])

In [68]:
subset_sample_arr[:]=10
subset_sample_arr

array([10, 10, 10, 10])

## TWO DIMENSIONAL ARRAYS

In [72]:
import numpy as np

In [73]:
matrix=np.array([[30,2,1],[11,6,9],[223,55,87]])
matrix

array([[ 30,   2,   1],
       [ 11,   6,   9],
       [223,  55,  87]])

In [74]:
matrix[1,2] #row,column

9

In [77]:
matrix[2,:]

array([223,  55,  87])

In [76]:
matrix[2]

array([223,  55,  87])

In [81]:
matrix[:,[1,2]]

array([[ 2,  1],
       [ 6,  9],
       [55, 87]])